name: CI Pipeline

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  test:
    runs-on: ubuntu-latest  # Using an Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.15'  # Specify your Python version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests using pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
