name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu as the runner OS

    steps:
      # Checkout the code to the runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python (specify the Python version)
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install build dependencies (including necessary C build tools)
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential python3-dev

      # Upgrade pip and setuptools
      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      # Install the requirements from the requirements.txt
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      # Run tests (e.g., using pytest)
      - name: Run tests
        run: |
          pytest
